# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='temperature',
            field=models.FloatField(default=37),
            preserve_default=False,
        ),
    ]
