# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0002_auto_20180405_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
