# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0005_auto_20180504_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 3, 7, 45, 548428)),
        ),
    ]
