# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 21:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0008_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 3, 16, 9, 444631)),
        ),
    ]
