# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 21:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0009_auto_20180504_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.AddField(
            model_name='data',
            name='date_values',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 2, 3, 18, 27, 710097)),
        ),
    ]
