# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollution_data', '0010_auto_20180504_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='date_values',
        ),
    ]
